/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.pss.dadosclima.view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;

/**
 *
 * @author UFES
 */
public class IncluirFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form IncluirFrame
     */
    public IncluirFrame() {
        initComponents();
        setVisible(true);
    }

    public JFormattedTextField getDataField() {
        return DataField;
    }

    public JButton getIncluirButton() {
        return IncluirButton;
    }

    public JFormattedTextField getPressaoField() {
        return PressaoField;
    }

    public JFormattedTextField getTemperaturaField() {
        return TemperaturaField;
    }

    public JFormattedTextField getUmidadeField() {
        return UmidadeField;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataLabel = new javax.swing.JLabel();
        TemperaturaLabel = new javax.swing.JLabel();
        UmidadeLabel = new javax.swing.JLabel();
        PressaoLabel = new javax.swing.JLabel();
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        DataField = new javax.swing.JFormattedTextField(format);
        TemperaturaField = new javax.swing.JFormattedTextField();
        UmidadeField = new javax.swing.JFormattedTextField();
        PressaoField = new javax.swing.JFormattedTextField();
        IncluirButton = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Incluir dados de clima");
        setOpaque(true);
        setVisible(true);

        DataLabel.setLabelFor(DataField);
        DataLabel.setText("Data:");
        DataLabel.setOpaque(true);

        TemperaturaLabel.setLabelFor(TemperaturaField);
        TemperaturaLabel.setText("Temperatura:");

        UmidadeLabel.setLabelFor(UmidadeField);
        UmidadeLabel.setText("Umidade:");

        PressaoLabel.setLabelFor(PressaoField);
        PressaoLabel.setText("Pressão:");

        DataField.setToolTipText("dd/mm/yyyy");
        DataField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DataFieldFocusGained(evt);
            }
        });
        DataField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataFieldActionPerformed(evt);
            }
        });

        TemperaturaField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        UmidadeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        UmidadeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmidadeFieldActionPerformed(evt);
            }
        });

        PressaoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        IncluirButton.setText("Incluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UmidadeLabel)
                            .addComponent(PressaoLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(IncluirButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PressaoField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UmidadeField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataLabel)
                            .addComponent(TemperaturaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TemperaturaField)
                            .addComponent(DataField, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataLabel)
                    .addComponent(DataField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TemperaturaLabel)
                    .addComponent(TemperaturaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UmidadeLabel)
                    .addComponent(UmidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PressaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PressaoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(IncluirButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataFieldActionPerformed

    private void UmidadeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmidadeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UmidadeFieldActionPerformed

    private void DataFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DataFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DataFieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DataField;
    private javax.swing.JLabel DataLabel;
    private javax.swing.JButton IncluirButton;
    private javax.swing.JFormattedTextField PressaoField;
    private javax.swing.JLabel PressaoLabel;
    private javax.swing.JFormattedTextField TemperaturaField;
    private javax.swing.JLabel TemperaturaLabel;
    private javax.swing.JFormattedTextField UmidadeField;
    private javax.swing.JLabel UmidadeLabel;
    // End of variables declaration//GEN-END:variables
}
