/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.pss.dadosclima.view;

import javax.swing.JFormattedTextField;

/**
 *
 * @author UFES
 */
public class MediaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MediaFrame
     */
    public MediaFrame() {
        initComponents();
    }

  

    public JFormattedTextField getPressaoField() {
        return PressaoField;
    }

    public JFormattedTextField getTemperaturaField() {
        return TemperaturaField;
    }

    public JFormattedTextField getUmidadeField() {
        return UmidadeField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TemperaturaLabel = new javax.swing.JLabel();
        UmidadeLabel = new javax.swing.JLabel();
        PressaoLabel = new javax.swing.JLabel();
        TemperaturaField = new javax.swing.JFormattedTextField();
        UmidadeField = new javax.swing.JFormattedTextField();
        PressaoField = new javax.swing.JFormattedTextField();

        setIconifiable(true);
        setTitle("Dados médios");

        TemperaturaLabel.setText("Temperatura:");

        UmidadeLabel.setText("Umidade:");

        PressaoLabel.setText("Pressão:");

        TemperaturaField.setEditable(false);
        TemperaturaField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##,#0"))));
        TemperaturaField.setFocusable(false);

        UmidadeField.setEditable(false);
        UmidadeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        UmidadeField.setFocusable(false);

        PressaoField.setEditable(false);
        PressaoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        PressaoField.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PressaoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TemperaturaLabel)
                            .addComponent(UmidadeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UmidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TemperaturaField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PressaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TemperaturaLabel)
                    .addComponent(TemperaturaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UmidadeLabel)
                    .addComponent(UmidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PressaoLabel)
                    .addComponent(PressaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField PressaoField;
    private javax.swing.JLabel PressaoLabel;
    private javax.swing.JFormattedTextField TemperaturaField;
    private javax.swing.JLabel TemperaturaLabel;
    private javax.swing.JFormattedTextField UmidadeField;
    private javax.swing.JLabel UmidadeLabel;
    // End of variables declaration//GEN-END:variables
}
